### ISSUE TITLE
Host name conflict, retrying with hassio-xx

### ISSUE THREAD

**Issue by invamped** [hassio-addons/addon-homebridge#14]
**Problem/Motivation**
Homebridge won't start up and get stuck in a loop with a Host name conflict.

**Expected behavior**
Expect homebridge to start and to produce a 'Key' for the Home.app

**Actual behavior**
Keeps trying to start service then fails and tries again with a new host name.

**Steps to reproduce**
Standard steps to add add-on

**Proposed changes**
No sure.

Example of log:
Host name conflict, retrying with hassio-19
Registering new address record for fe80::473e:1cc1:fccc:1af7 on vetha58f892.*.
Registering new address record for 169.254.70.152 on vetha58f892.IPv4.
Registering new address record for fe80::786e:31ff:fec6:1b78 on veth175236b.*.
Registering new address record for 169.254.104.131 on veth175236b.IPv4.
Registering new address record for fe80::a1db:7d77:9e6f:9e14 on docker0.*.
Registering new address record for 169.254.1.224 on docker0.IPv4.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::3802:117a:5c87:c173 on hassio.*.
Registering new address record for 169.254.52.243 on hassio.IPv4.
Registering new address record for 172.30.32.1 on hassio.IPv4.
Registering new address record for fe80::d435:ef2d:f54a:aaa2 on wlan0.*.
Registering new address record for 192.168.1.102 on wlan0.IPv4.
Registering new address record for fe80::a5e3:9aca:38b3:2173 on eth0.*.
Withdrawing address record for fe80::473e:1cc1:fccc:1af7 on vetha58f892.
Withdrawing address record for fe80::786e:31ff:fec6:1b78 on veth175236b.
Withdrawing address record for 169.254.104.131 on veth175236b.
Withdrawing address record for fe80::a1db:7d77:9e6f:9e14 on docker0.
Withdrawing address record for 169.254.1.224 on docker0.
Withdrawing address record for 172.17.0.1 on docker0.
Withdrawing address record for fe80::3802:117a:5c87:c173 on hassio.
Withdrawing address record for 169.254.52.243 on hassio.
Withdrawing address record for 172.30.32.1 on hassio.
Withdrawing address record for fe80::d435:ef2d:f54a:aaa2 on wlan0.
Withdrawing address record for 192.168.1.102 on wlan0.
Withdrawing address record for fe80::a5e3:9aca:38b3:2173 on eth0.
Host name conflict, retrying with hassio-20

This just keeps repeating, hassio-21, 22 etc and never starts.
I'm trying to run this on a raspberrry pi 2, raspbian.

Any ideas?

Thanks

**Comment by invamped** [comment]
Anyone?

**Comment by jay448** [comment]
I have the exact same issue. Did you fix this yet?

**Comment by invamped** [comment]
No sadly. I've had it produce the code, but still not show up on iOS. Check the log again and it stuck in that loop again. Please let me know if you figure it out. Cheers

**Comment by jay448** [comment]
Sadly I have not been able to solve this issue either. I have tried to do some digging on the internet but was not able to find anything except for this post. Guess we will have to wat for the developer @frenck  to figure it out or something.

**Comment by jay448** [comment]
Just to give a little extra info. I am running this in a regular Linux enviroment and what I have read if i'm not wrong it's a know issue. It should be fixed in 1.1.0. Not sure if my info is correct but we just have to wait and see.

**Comment by jay448** [comment]
@invamped I found the fix!. I had to change something in my avahi config. 
I had to do the following **nano /etc/avahi/avahi-daemon.conf** and edit host-name to say **host-name=hassio**. Then doing sudo service avahi-daemon restart and start the homekit addon. I am not getting the error anymore in the logs! Hopefully this will work for you too.

**Comment by stickystyle** [comment]
@jay448 Did you make that change on the linux host, or in the container? Because the container already has the config file as you specify https://github.com/hassio-addons/addon-homebridge/blob/d214ce440836bc137823d27f272e3df39e45541f/homebridge/files/avahi-daemon.conf#L2

**Comment by jay448** [comment]
@stickystyle I changed it on my Linux Host. This worked for me. Hopefully it will for you too.

**Comment by invamped** [comment]
Hey! Sorry for the late reply, but @jay448 your solution worked for me also. HA now shows up under iOS and controls work great. Thanks for your help. 

Thanks
