### ISSUE TITLE
Updated to 1.0.2, Accessories disappeared

### ISSUE THREAD

**Issue by madsci954** [hassio-addons/addon-homebridge#2]
## Problem/Motivation

> HomeBridge still in iOS but no accessories. Restart of HomeBridge gives "Please set default_visibility in config.json to "hidden" or "visible"." 

## Proposed changes

> In a default cong.json, add where this default_visibility should be.

**Comment by madsci954** [comment]
Nevermind, I figured it out. Issue can be closed.

**Comment by frenck** [comment]
Thank you for reporting this issue.
I leave this one open. I do agree on adding the line to the configuration by default.

For existing installations, I can't change the configuration, but adding it for new users would be helpful.
