### ISSUE TITLE
Cannot pull home bridge add-on - 404 error

### ISSUE THREAD

**Issue by mkgreco** [hassio-addons/addon-homebridge#20]
## Problem/Motivation

I cannot pull the home bridge add-on via hass.io. Only the homebridge add-on is affected, the terminal and SSH addons work just fine.
The error is:
```
17-09-27 19:05:49 INFO (SyncWorker_7) [hassio.dock.interface] Pull image hassioaddons/homebridge-armhf tag 1.0.3.
17-09-27 19:05:52 ERROR (SyncWorker_7) [hassio.dock.interface] Can't install hassioaddons/homebridge-armhf:1.0.3 -> 404 Client Error: Not Found ("no such image: hassioaddons/homebridge-armhf:1.0.3: No such image: hassioaddons/homebridge-armhf:1.0.3").
```

I'm unable to determine exactly why it's happening - but I suspect it's due to:
https://github.com/hassio-addons/repository/blob/master/homebridge/config.json

Line 22 references "hassioaddons/homebridge-{arch}" and not what I suspect should be "hassio**-**addons/homebridge-{arch}" as referenced elsewhere.

(but that's just a best guess)

**Comment by frenck** [comment]
The image name looks correct and is showing on:
https://hub.docker.com/r/hassioaddons/homebridge-armhf/tags/

I'm not sure what is causing this to be honest.

**Comment by frenck** [comment]
I am closing this issue, since it went stale. 
If you want to discuss it further, please feel free to re-open the issue.
