### ISSUE TITLE
Homebridge don't see Wireless Switch

### ISSUE THREAD

**Issue by WEZANGO** [hassio-addons/addon-homebridge#21]
## Problem/Motivation

Wireless switch from Xiaomi Aqara is avaliable on HA, but not visible in iOS home app. It works fine when using Homebridge without hassio, but not avaliable with that plugin. Any suggestions how to fix it? Thanks!

**Comment by frenck** [comment]
Hi @WEZANGO,

This sounds like an issue with Homebridge itself, not the add-on. The add-on just wraps Homebridge and makes it available, we don't actually develop Homebridge ourselves.

I don't own any Xiaomi product, so I am not able to reproduce or provide you answers.

Please check it with the Homebridge project, the Home Assistant - Homebridge plugin project, or you could try the community forums.
