### ISSUE TITLE
no accessories in home app on ios 11

### ISSUE THREAD

**Issue by jfayre** [hassio-addons/addon-homebridge#23]
I am attempting to add my hassio homebridge instance to home kit on IOS 11. I am able to add the homebridge bridge, but none of my sensors show up. The home app tells me that I need to perform additional setup in order to add accessories. 
When I try to access the accessories list, it is empty.

I have tried restarting homebridge as well as remove and re-adding homebridge in the home app on IOS. Homebridge is seeing my sensors, so I know it is connecting to homeassistant correctly.

**Comment by frenck** [comment]
Have you tried the following:

https://github.com/hassio-addons/addon-homebridge#faq

?

**Comment by jfayre** [comment]
Hi,

I have. 

The phone does see homebridge, but none of my sensors or switches are showing up in the home app.

**Comment by frenck** [comment]
Sound like your devices are hidden by default.

Do you have the following line:

`"default_visibility": "visible",`

in your home bridge configuration?

**Comment by jfayre** [comment]
Ah! That did it! Did I just miss something? I didn’t see that documented anywhere that you needed to add that line.

Thanks!

**Comment by frenck** [comment]
@jfayre I'm glad it worked out!

No, I guess you did not miss something, maybe you accidentally deleted the line? Reused an older configuration?

Nevertheless, the line is in the default configuration, so it should have been there.

Closing this issue, since the problem at hand has been resolved.
