### ISSUE TITLE
Siri will not lock or unlock a door.  Home app will do this just fine.

### ISSUE THREAD

**Issue by djmcp** [hassio-addons/addon-homebridge#26]
## Problem/Motivation

When requesting Siri lock a door, it reports back that it was locked but logging shows it was unlocked.  

"Siri, lock the front door":

[8/25/2017, 7:13:04 PM] [Wink] Sending update: Front Door (lock/170874) { locked: false }
[8/25/2017, 7:13:04 PM] [Wink] Update sent successfully: Front Door (lock/170874)
Home app > unlock the front door:

[8/25/2017, 7:14:41 PM] [Wink] Sending update: Front Door (lock/170874) { locked: true }
[8/25/2017, 7:14:41 PM] [Wink] Update sent successfully: Front Door (lock/170874)

## Expected behavior

Lock the door

## Actual behavior

Door remains unlocked

## Steps to reproduce

Request Siri to unlock or lock a door.  It will report back that the command worked, but nothing happens.

## Proposed changes

This was addressed in nfarina's homebridge instance by uplifting happ-nodejs:

https://github.com/nfarina/homebridge/issues/1466
https://github.com/nfarina/homebridge/commit/e874061b89e724f6a524341238b84221d0142555

**Comment by frenck** [comment]
This will require an upgrade of Homebridge withing the addon.
Will add it to the roadmap.

**Comment by frenck** [comment]
This issue is fixed in v2.0.0 of the add-on.

**Comment by djmcp** [comment]
Thanks @frenck!  I updated this evening and it works like a charm!
