### ISSUE TITLE
Homebridge will not show in iOS app / Possible mDNS conflict

### ISSUE THREAD

**Issue by frenck** [hassio-addons/addon-homebridge#3]
> This issue originated from hassio-addons/repository#5 by @marcelveldt

> This issue originated from hassio-addons/repository#2 by @mihalski

## Problem/Motivation

Homebridge won't show up in the Home app on my iOS device.
I've also checked with Bonjour Browser from my Mac and I don't see any references there to Homebridge.

## Expected behavior

Homebridge/Homeassistant should show up in my Home app on iOS as accessory so I can connect with the PIN and have it discovering my devices.

## Actual behavior

Homebridge doesn't show up at all.
I do notice some related error in the log:
Host name conflict, retrying with hassio-15

It should be noted that I changed the default hassio hostname to "home assistant" instead of "hassio".

## Steps to reproduce

Not sure, just followed the default configuration steps.

## Proposed changes

I did not yet test it, but I suppose it's related to the hostname change.

Full log attached
[homebridge_log.txt](https://github.com/hassio-addons/repository/files/1224769/homebridge_log.txt)

**Comment by frenck** [comment]
This issue is fixed in v2.0.0 of the add-on.

**Comment by alvnas1500** [comment]
I am using v2 with same problem.

**Comment by frenck** [comment]
@alvnas1500 v2.x.x has options to circumvent special cases with options provided in the add-on configuration. If you still encounter an issue, please create a new issue and please add the configuration used and some logs. This way we can help or maybe determine an issue to solve.

Thanks 🏅
