### ISSUE TITLE
Nest temperature incorrect on homekit

### ISSUE THREAD

**Issue by mceres** [hassio-addons/addon-homebridge#37]
The Nest temperature from Nest that is in F is being threaded as  C and then being converted to F.

For example Nest is set to 76 F while on the homekit app it shows as 169. Could this be an issue with Homebridge or Hassio?

Is there a fix already for this?

i am using Hass.io 0.55.2 and Homebridge 1.0.3

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with Homebridge and maybe the Home Assistant Homebridge plugin (which both are used by this add-on).

I've found a related issue here: https://github.com/home-assistant/homebridge-homeassistant/issues/222
