### ISSUE TITLE
After the upgrade of version 2.0, the data obtained from the temperature and humidity sensors of the xiao mi  is 0

### ISSUE THREAD

**Issue by leapp** [hassio-addons/addon-homebridge#43]
After the upgrade of version 2.0, the data obtained from the temperature and humidity sensors of the xiao mi  is 0.   T T

**Comment by frenck** [comment]
@leapp That is a pretty short report. I do not use Xiaomi sensors myself, so please provide me with more information. Like logs. Try enabling the Homebridge log function in `/config/homebridge/config.json` and put the `log_level` option of the add-on into debug mode. This will give you more output.

**Comment by siewyc** [comment]
This issue is fixed with HA 0.56.1.
