### ISSUE TITLE
Osram Lightify Tunable Bulbs : Temperature cannot be controlled via Home app

### ISSUE THREAD

**Issue by swamaway** [hassio-addons/addon-homebridge#46]
Osram lightify bulbs ( tunable bulbs) do not respond to changes in color temperature settings made through the Home app (iOS) but do so through the Hassio frontend. 

The bulbs support several colors throughout the white spectrum (color temperature) but default to white when controlled through homebridge.

I have used this setup directly through Homebridge (run directly on Rasbian) with the Osram-lightify platform and this feature worked as expected before. This does not work when using the homebridge addon (2.0.0) on the Hassio build (0.56.1). Unfortunately, I didnt test this with earlier versions, so I dont know if the new upgrades broke some support or if this issue was preexisting

**Comment by frenck** [comment]
Thank you for reporting your issue. Nevertheless, the add-on itself does not do anything with the logic of Homebridge or the Home Assistant plugin. 

I would suggest you'd create an issue with the Home Assistant Homebridge plugin repository. Please be sure to attach some logs when creating that issue.
