### ISSUE TITLE
node old version

### ISSUE THREAD

**Issue by dasam** [hassio-addons/addon-homebridge#47]
# Problem/Motivation

integration with telldus stopped working in hass.io see : https://github.com/jchnlemon/homebridge-telldus/issues/55

## Expected behavior

telldus plugin was upgraded, to support node 8, expected hass.io to also work

## Actual behavior

didnt work

## Steps to reproduce

reproducable in hass.io

## Proposed changes

upgrade node

**Comment by frenck** [comment]
The change has been merged into the `master` branch and will be included in the next release.
Thanks for reporting the change request @dasam! 🏅

**Comment by dasam** [comment]
awesome! Good work, i am glad to help :-)
