### ISSUE TITLE
How to control Nest temperature/away status?

### ISSUE THREAD

**Issue by iAmRenzo** [hassio-addons/addon-homebridge#59]
I've added Homebridge to my Hass.io installation and it works fine. I have items default hidden because Hue already is in my HomeKit. But I want to add only Nest.

These are all Nest items:
binary_sensor.living_room_thermostat_fan
binary_sensor.living_room_thermostat_has_leaf
binary_sensor.living_room_thermostat_is_locked
binary_sensor.living_room_thermostat_is_using_emergency_heat
binary_sensor.living_room_thermostat_online
climate.living_room
sensor.living_room_thermostat_humidity
sensor.living_room_thermostat_hvac_state
sensor.living_room_thermostat_operation_mode
sensor.living_room_thermostat_target
sensor.living_room_thermostat_temperature

But which one will show up as a thermostat inside HomeKit? Which one of these do I have to make visible to show up in HomeKit?

**Comment by frenck** [comment]
Hi there,

Thank you for creating an issue. Nevertheless, this issue is not add-on specific.
Please check with the authors of https://github.com/home-assistant/homebridge-homeassistant. Or maybe use the community forum, since this is actually a configuration thingy.

Thx!

**Comment by iAmRenzo** [comment]
Is it?
When I used the plain (non hassio) nodejs + homebridge + nest plugin there was just one Nest entity which actually worked directly.
New there are several sensors and binary sensors and I cannot find the one to control the Nest.

**Comment by frenck** [comment]
Recently newer versions of Homebridge and the Home Assistant plugin where released. Maybe that is causing the issue?

This add on does not modify that code. The working of the plugin and Homebridge are not part of this add on or repository.
