### ISSUE TITLE
Cameras missing from config.json

### ISSUE THREAD

**Issue by netmanchris** [hassio-addons/addon-homebridge#60]
# Problem/Motivation

Looking at generated config.json.  Should “cameras” be added to the “supported types” array to expose camera feeds ( FFMpeg ) components registered to HASSIO to Homebridge? 

Feel free to point to docs for the format. Happy to contribute to documentation if that helps!
## Expected behavior

If a camera ( Netatmo Welcome, Ring Doorbell Pro ) component is registered with the FFMpeg and is displaying images on the HASSIO homepage properly, I would expect that the cameras should be automatically exposed through homebridge to Apple Homekit apps as well. 
## Actual behavior

No cameras are exposed. Other devices are registered and available as Homekit accessories as expected.

**Comment by frenck** [comment]
Camera's are not actually supported by the `homebridge-homeassistant` plugin, which forms the basis of this add-on and its default configuration.

Right?

**Comment by netmanchris** [comment]
LOL Absolutely. Just getting up to speed!  Appreciate the quick answer!
