### ISSUE TITLE
Problems with Panasonic Viera with Hass.io/Homebridge combination

### ISSUE THREAD

**Issue by iAmRenzo** [hassio-addons/addon-homebridge#61]
I have problems with the Panasonic Viera component. I have it also in Home Assistant. So I know it isn't HomeBridge, I think, but... When I was running NodeJS/HomeBridge on my Pi I used this plugin (https://www.npmjs.com/package/homebridge-panasonictv). I was wondering, is there a way to get this inside HomeBridge?! So I don't have to use the Hass.io component Viera?

**Comment by frenck** [comment]
You can load additional plugins using the add-on configuration.
Please read the documentation:

https://github.com/hassio-addons/addon-homebridge#option-plugins

**Comment by iAmRenzo** [comment]
I've found that one, but I didn't see the TV popping up in my HomeKit

`{
  "log_level": "info",
  "avahi_interfaces": "",
  "avahi_hostname": "",
  "avahi_domainname": "local",
  "enable_ipv6": true,
  "packages": [],
  "init_commands": [],
  "plugins": [
    "homebridge-panasonictv"
  ]
}`
and my config.json

`{
  "bridge": {
    "name": "Hassio",
    "username": "B8:27:EB:5C:78:87",
    "port": 51826,
    "pin": "262-14-631"
  },
  "description": "Homebridge for Home Assistant",
  "accessories": [],
  "platforms": [
    {
      "platform": "HomeAssistant",
      "name": "HomeAssistant",
      "host": "http://hassio/homeassistant",
      "password": "",
      "default_visibility": "hidden",
      "supported_types": [
        "automation",
        "binary_sensor",
        "climate",
        "cover",
        "device_tracker",
        "fan",
        "group",
        "input_boolean",
        "light",
        "lock",
        "media_player",
        "remote",
        "scene",
        "script",
        "sensor",
        "switch",
        "vacuum"
      ],
      "logging": true,
      "verify_ssl": true
    }
  ]
}
`

**Comment by frenck** [comment]
@iAmRenzo, please ask the question with the author(s) of the panasonictv plugin for Homebridge. Obviously, I cannot provide support for all plugins.

**Comment by iAmRenzo** [comment]
I know that. But with three systems (hassio, homebridge for hassio and third party plugin) it's kind of difficult to troubleshoot the problem.
Homebrigde is working fine, default setting is to hide everything in homekit and I mark the items visible in the hassio configuration files.
But does this effect the added plugin? Or is it bypassing hassio completely. 
If the latter is the case I can check the plugin author and see if I have everything needed for the plugin to work. If it's the first, the third party plugin doesn't matter, right?

Too bad you don't answer anymore :(
