### ISSUE TITLE
Envisalink/Security System Not Updating Status Until Opened

### ISSUE THREAD

**Issue by erfind** [hassio-addons/addon-homebridge#63]
# Problem/Motivation

I use Home Assistant in partnership with an Envisalink and homebridge plugin to carry out security functions. Right now, the status of the alarm doesn't update unless the Home app is opened on my iPhone. (This is a problem, as it is supposed to send a notification when the alarm is armed or disarmed.)

## Expected behavior

Whenever there is a state change, Home Assistant and Homebridge should pass the data to HomeKit to send an alert that there has been a change in the arm/disarm status.

## Actual behavior

The system only updates whenever the Home App is opened.

## Steps to reproduce

Set alarm manually or via the home assistant, or through automation, and then you are not alerted.  You must then open the Home app to let it connect to Home Assistant/Homebridge to update. Then an alert comes up that says what happened.

## Proposed changes

I am unsure of how to fix this.  I know that in the past there was a similar issue with homebridge itself before I started using Home Assistant, however, I do not know how this was fixed.

**Comment by oktemplar** [comment]
I am seeing the same with my Hass.IO install + Envisalink. For me this is not limited to the Envisalink though, every time I open the Home app on iOS all of my HA accessories bridged to HomeKit show as "Updating". It takes 20-30 seconds then everything shows correctly. This occasionally creates problems with Siri on my watch as it will tell me the accessories I want to use are not available. For info I have duckdns + Lets Encrypt enabled. I did not try using Homebridge prior to having encryption turned on so can't answer to that being the issue. I did try changing verify_ssl option to false but this didn't help. Can provide more info if it helps anyone!

**Comment by heathpitts** [comment]
I had a somewhat similar issue to this. My Hass.io setup includes an envisalink module as well. Notifications would never fire until the Home app was opened up. Also, actual native HomeKit devices wouldn’t fire until the app was opened either.  Here’s how I “fixed” it. I’m running a few add ons on my Hass.io box including Frenck's Homebridge and pi-hole add ons. However, when running Homebridge on the same hassio instance with pi-hole and it having to use itself for DNS, this issue shows up. Either moving Homebridge to another RPi or setting DNS to be a different box made this start working again.

**Comment by oktemplar** [comment]
I'm not running pi-hole, but it definitely could be due to running Homebridge/Hass.io on the same box. Unfortunately I don't have another RPi sitting around to use as a dedicated Homebridge :(

At the moment I'm just living with it, I've found lately that most of my HA switches still respond by Siri from any of my devices, it's really just a hassle when I want to open the Home app. I have some HomeKit only devices in there that I can only update thru Home so that's a bit of a bummer, but not killing me or anything.

**Comment by frenck** [comment]
This is an upstream issue. Please check this with the HomeBridge developers.
