### ISSUE TITLE
I cant pick colors on the color picker in from siri or the home app

### ISSUE THREAD

**Issue by ollisier** [hassio-addons/addon-homebridge#65]
# Problem/Motivation

I need to be able to change colors from the home app but they don't change

## Expected behavior

When i pick a color over homekit it will change the color of the lamp

## Actual behavior

Only the first time i try to change the color from  my iphone after i have changed the color from home assistant does it update. It doesnt update the color on the Hassio web interface so it is something to do with the plugin, not the lights.

## Steps to reproduce

try changing colors of an rgb device

**Comment by frenck** [comment]
Thank you for your bug report.
This seems like an issue with Homebridge or the Home Assistant Homebridge plugin and is not something this add-on has a part in.

I would suggest opening the issue at the Home Assistant Homebridge repository:
https://github.com/home-assistant/homebridge-homeassistant
