### ISSUE TITLE
Unable to access Homebridge devices when not home

### ISSUE THREAD

**Issue by DennisBerggren** [hassio-addons/addon-homebridge#66]
# Problem/Motivation

When I'm not at home I can no longer get status or control my HomeBridge devices in the Home app on the iPhone. All my non-HomeBridge devices still works just as they should so it's only the devices that I run via HomeBridge that is the problem.

It all worked before but since some time back it stopped working. 

My setup is:
Raspberry Pi 3b running Hass.io 0.59.2
Homebridge 2.2.0 (auto update enabled)
Apple TV with latest OS
iPhones and iPad with latest OS

Homebridge and Apple TV is connected to the same Switch

Fibaro, Elgato, IKEA and Philips Hue devices still work to control over 3G/4G.

See screenshots for behaviour over Wi-Fi vs 4G:
![img_4539](https://user-images.githubusercontent.com/34687348/34167442-1ba67a04-e4e2-11e7-805f-ccfdb40bc0f4.PNG)
![img_4540](https://user-images.githubusercontent.com/34687348/34167444-1bc9291e-e4e2-11e7-8ec8-602b93eee869.PNG)

## Expected behavior

Possible to get status and control devices also over 4G/3G connection

## Actual behavior

All HomeBridge devices are shown as "No Response"

## Steps to reproduce

Disconnect wifi on the iPhone and try to access the Homebridge devices. 

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Sound like your AppleTV is not enrolled into the Home feature?

**Comment by sethhere04** [comment]
I am also having this issue, My other devices that are directly connected to homekit are working so I know my apple tv is connected.

**Comment by DennisBerggren** [comment]
The ATV is for sure the hub. Just like sethhere04 is writing the other Homekit devices are shown.

However after some time I have found a workaround that works. Logging out and in again on the ATV after a restart of Homebridge seems to fix the issue again for a while.

**Comment by frenck** [comment]
There are a lot of "known" issues with the HomeKit / iCloud sync. Maybe you experienced one. Logging in and out indeed fixes the issue a lot of the time (forces the sync).
