### ISSUE TITLE
Save button disabled when modifying Options - can't save

### ISSUE THREAD

**Issue by B1tMaster** [hassio-addons/addon-homebridge#73]
# Problem/Motivation
 Tried to add a homebridge-foscam plugin
https://www.npmjs.com/package/homebridge-foscam

  Options menu, would not let me save changes as soon as I added additional JSON config options.
 "SAVE" button greyed out as soon as 
## Expected behavior

Once added new parameters to JSON, I expect to be able to save those changes.
> (What you expected to happen)

## Actual behavior

SAVE button greyed out

SAVE button on Options greyed out and not allowing to save .
## Steps to reproduce

add below additional config:

  ```
"plugins": ["homebridge-foscam"],
  "accessories": [{
    "accessory": "foscam",
    "name": "LivingRoomFoscam",
    "username": "my-admin",
    "password": "your-password",
    "host": "192.168.10.14",
    "port": "80"}]
}

```
Note that "accessories" is a NEW section to JSON that is required for plugin configuration. 

## Proposed changes

Not sure if this is some sort of JSON validation error from hassio or validation from plugin itself.
I don't have a solution, but this seem like a bug .

**Comment by frenck** [comment]
The JSON you have is invalid, check it with https://jsonlint.com/

This is Hass.io behavior, if the JSON config is invalid, it will block the save button. This is not an add-on issue, therefore closing this one.
