### ISSUE TITLE
homebirdge-versions

### ISSUE THREAD

**Issue by Kugelfang666** [hassio-addons/addon-homebridge#74]
Hi,

i'm having an issue where this plugin installes v0.4.33 of homebirdge while a plugin (homebirdge-hue) has an dependancy on v0.4.36. Is it somehow possible to either pull the latest version of homebirdge or to select a specified version of a plugin to install instead of thel latest one?

**Comment by frenck** [comment]
The add-on needs to be updated.
I've placed this issue on my short list. Thank you for reporting this to me.

**Comment by frenck** [comment]
Homebridge has been updated in `v2.3.0` of the add-on.
