### ISSUE TITLE
homebirdge-versions similar to #74

### ISSUE THREAD

**Issue by Kugelfang666** [hassio-addons/addon-homebridge#77]
Hi,

i again encountered the same problem as in inssue 74. The homebridge-hue addon needs the latest homebirdge version. It would be great if you could look into this and update from 0.4.36 to 0.4.38.

I guess this problem will reoccour everytime the minimum dependancy for an plugin is pushed up. it would be great if this could be permanently fixed by enabling to specify dedicated versions of the plugins to be loaded.

**Comment by funnybutrandom** [comment]
Could the docker file not be set to just run homebridge@latest

**Comment by jsaunders92** [comment]
It would be great if this could be updated as I have a plugin that requires version 0.4.38 too.

**Comment by frenck** [comment]
@funnybutrandom No, it cannot be set to latest. That is not how these Docker images work.

I'm currently offline for a couple of weeks. I expect to be back next week (moving into my new house). Normally I'm up to date, but currently lacking access to internet and time to ship updates.

So please, bear with me for another week.

**Comment by frenck** [comment]
I've updated the add-on code to include the latest versions, which is now merged into the `master` branch. A new release will be out soon.
