### ISSUE TITLE
Loading 0 accessories

### ISSUE THREAD

**Issue by carson512** [hassio-addons/addon-homebridge#78]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by carson512** [comment]
This is the log file

Server startup complete. Host name is hassio.local. Local service cookie is 21579210.
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-2-13 23:37:18] Loaded plugin: homebridge-homeassistant
[2018-2-13 23:37:19] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2018-2-13 23:37:19] ---
[2018-2-13 23:37:19] Loaded config.json with 0 accessories and 1 platforms.
[2018-2-13 23:37:19] ---
[2018-2-13 23:37:19] Loading 1 platforms...
[2018-2-13 23:37:19] [HomeAssistant] Initializing HomeAssistant platform...
[2018-2-13 23:37:19] [HomeAssistant] Fetching HomeAssistant devices.
[2018-2-13 23:37:19] Loading 0 accessories...
[2018-2-13 23:37:19] [HomeAssistant] Received event: ping

I have the xiaomi_aqara hub.
the homebridge can't find it.
what's wrong?

**Comment by vlinder** [comment]
I had this exact problem. The problem started after upgrading to 2.3.0. After a few hours of trouble shooting, reinstalling homebridge and a lot of other crap I found the setting `default_visibility` which now was set to `hidden`. Changing it to `visible` brought back all my devices/accessories.

Looking in this projects changelog they specifically mention changing it to `hidden` as a default but only for new installs. I don't know why it stopped working for me all of a sudden but this fixed it now at least.

There are other better ways of deciding which accessories to show in homebridge apparently but I have not figured out how to configure it yet. One should do it in the `customize.yml` file I think.

**Comment by seanh1995** [comment]
i had the same problem but followed vlinder guild and got my devices to load but now i cant connect in the home app

**Comment by frenck** [comment]
The issue is indeed caused by the new default setting. I've changed the default to match the original homebridge Home Assistant plugin (this way, the docs and behavior matches).

@hibskids Please follow the steps in the manual of the add-on. It contains hints on restoring the connection in the FAQ.

**Comment by inchlogic** [comment]
Hi. Have changed to visible however accessories are still not showing. Is it worth uninstalling and reinstalling. Do I need to manually add each accessory somewhere or shod they auto detect? I use basic switches so should not be complicated.
