### ISSUE TITLE
HomeAssistant not exposed on port 8123

### ISSUE THREAD

**Issue by l00mi** [hassio-addons/addon-homebridge#8]
## Problem/Motivation

Homebridge does not work as it expects to connect to port 8123 and thus fails.

## Expected behavior

An option to change the HomeAssitant URL would be splendid! A way to introspect the current Hassio URL even splenditer.

**Comment by perwramdemark** [comment]
@l00mi Have you tried setting the URL in /config/homebridge/config.json?

**Comment by l00mi** [comment]
Hm, how would I change this file?

Is this possible in Hass.io Gui?

**Comment by perwramdemark** [comment]
I assume you're running hassio on a Rpi or the likes.

Easiest thing is to install the add-on https://home-assistant.io/addons/samba/ after that you can connect to the rpi from another computer and you'll find the file in /config/homebridge/config.json and can edit it with your favourite editor.

**Comment by l00mi** [comment]
Okay I see, but the idea to make it configurable through the add-on itself is not wrong? Or what do you think?

**Comment by perwramdemark** [comment]
Sure, I suppose they could have had the config in the "Options" through the hassio GUI.

**Comment by perwramdemark** [comment]
@l00mi Let me know if you get it running, I haven't succeeded, getting a 403 during startup.

**Comment by frenck** [comment]
My first thought: Good idea... but 2 seconds later... removed the tags again.
This is part of the Homebridge configuration in `/config/homebridge/config.json`. This file remains untouched and is not "managed" by this add-on.

I could add a configuration value for it, but it will be useless after the first run.

**Comment by l00mi** [comment]
Hmm, but homebridge will not start without being able to connect to home-assistant?

**Comment by frenck** [comment]
@l00mi After the first start/try, the configuration files will appear in `/config/homebridge`. You will need to modify it and restart the addon.
