### ISSUE TITLE
Trying to add Homebridge to Home

### ISSUE THREAD

**Issue by dobrynski** [hassio-addons/addon-homebridge#83]
# Problem/Motivation

After a period of not using Homebridge I've tried to go back and I can't seem to add it.

## Expected behavior

I expect it to add the accessory.

## Actual behavior

Couldn't add Home Assitant accessory manually

## Steps to reproduce

Try to add Home Assitant accessory manually

## Proposed changes

No proposed changes. Suspect possible configuration problem?

![img_3945](https://user-images.githubusercontent.com/3755059/37096051-479c88ba-2263-11e8-94b3-21c425446589.PNG)

It's not clear what changes need to be made from the default config to allow things to work.

**Comment by Kugelfang666** [comment]
Had a similar problem once. Deleting the persist folder helped
