### ISSUE TITLE
Nest HA climate entity stopped working after 2.4.0 update

### ISSUE THREAD

**Issue by AndBobsYourUncle** [hassio-addons/addon-homebridge#84]
# Problem/Motivation

> I believe I've identified the recent update to cause the issue (2.4.0)

## Expected behavior

> For homekit to be able to fetch the status of the climate accessory (Nest connected to Home Assistant)

## Actual behavior

> My phone can fetch the status of any other accessory besides the climate one.

## Steps to reproduce

> Use a Nest climate entity in HA with the recent 2.4.0 version of this addon. Any Homekit app will never be able to fetch the current state of all homebridge accessories created for the Nest climate entity (fan, thermostat, etc.).

## Proposed changes

> It looks as though there was a recent change to the codebase for the homebridge-homeassistant package, and that update was included in this addon. Here is the relevant PR that was added to this release:

https://github.com/home-assistant/homebridge-homeassistant/pull/244

So, it appears as though there were recent changes to a core portion of the climate code. This added a "fan" accessory. I'm not too sure, but there might be a problem creating a fan accessory for the Nest component in HA. Perhaps the relevant attributes aren't present?

**Comment by frenck** [comment]
This is not related to the add-on, bit probably with the home-assistant/homebridge-homeassistant plguin of Homebridge.

Sorry m8, but I have to redirect your question in this case.
