### ISSUE TITLE
Received conflicting record / Host Name Conflict Error

### ISSUE THREAD

**Issue by w00master** [hassio-addons/addon-homebridge#86]
# Problem/Motivation

> After restarting HassIO (made changes to the Configuration.yaml - this passed the Config Check), restarted Homebridge, Homekit/Homebridge became "no response."  I had also just updated HassIO to 0.66.  Previous to restarting Homebridge, everything was working fine in Homekit/Homebridge.

## Expected behavior

> Considering I hadn't made any additions to Homebridge, nor made changes to config.json, nor added any packages, I had thought everything would be fine.  I was simply doing a reboot.

## Actual behavior

> Homekit showed "No Response."  in my logs, I show this:
>
> Received conflicting record [e.4.5.7.e.e.e.f.f.f.d.4.2.4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa	IN	PTR hassio-3965.local ; ttl=120] with local record to be. Withdrawing.
Withdrawing address record for 172.30.32.1 on hassio.
Withdrawing address record for fe80::36b3:5563:231f:286 on eth0.
Withdrawing address record for 192.168.0.104 on eth0.
Host name conflict, retrying with hassio-56
Registering new address record for fe80::42:4dff:feee:754e on hassio.*.
Registering new address record for 172.30.32.1 on hassio.*.
Registering new address record for fe80::36b3:5563:231f:286 on eth0.*.
Registering new address record for 192.168.0.104 on eth0.*.
dbus-entry-group.c: interface=org.freedesktop.Avahi.EntryGroup, path=/Client0/EntryGroup1, member=Reset
dbus-entry-group.c: interface=org.freedesktop.Avahi.EntryGroup, path=/Client0/EntryGroup1, member=Reset

## Steps to reproduce

> Unknown, I had just made changes to my Configuration.yaml (just added in some input_booleans). I did just recently upgrade to HassIO 0.66.

## Proposed changes

> Based on google searches, I updated my config to the following, but nothing has appeared to have changed:
> {
  "log_level": "trace",
  "avahi_interfaces": "eth0",
  "avahi_hostname": "hassio",
  "avahi_domainname": "local",
  "enable_ipv6": true,
  "packages": [],
  "init_commands": [],
  "plugins": []
}
>
> Any help would be appreciated!

**Comment by w00master** [comment]
As an update, I've uninstalled, reinstalled, provided a new HomeKit code, and changed the "username," I'm still getting these errors. 

I don't have any Homebridge plugins installed.  The only thing that was done previously was that I updated HassIO to 0.66 and I added in a new input_boolean.  This is why I needed to restart Homebridge in the first place.

**Comment by frenck** [comment]
Seems like the native HomeKit support of Home Assistant is active in your installation. They share the same port number. Since Home Assistant boots first, it wins.

Please configure a different HomeKit port number in either Home Assistant or the Homebridge configuration. Or (if you don't use native HomeKit support), disable it in Home Assistant.

**Comment by w00master** [comment]
Hmmmm.  I don't have the native Homekit installed on my HassIO instance?  All I have are the following add ons:

- Configurator
- Duck DNS
- Node-RED
- SSH Server
- Samba share

I've also double-checked my Configuration.yaml file and I do not have the native Homekit component in there.  Am I misinterpreting your ask?  Apologies if I am.

Here's my current Configuration.yaml (converted it into .txt so that I can upload it here). 
[Configuration.txt](https://github.com/hassio-addons/addon-homebridge/files/1868262/Configuration.txt)

**Comment by w00master** [comment]
As a follow-up, despite not having the "native" Homekit enabled (had no idea this rolled out), I went ahead and changed the port number in the config.json.  I am still getting the same errors/messages in the log.  Did I update the port # in the correct area?  if not, where should I change this?

As an aside, I changed the port # to a completely new one, twice.  Still the same errors.  Any help would be appreciated.

**Comment by TTDARK** [comment]
I am having the same problem.
I wanted to try homebridge-config-ui-x so I had to do a restart of homebridge today. Sadly that didn't work so I changed all configs back to what it was. And now it's spitting out the same logs as @w00master has posted. The Homekit component is not activated either.
Changing the port in config.json did not work for me either.

> [cont-init.d] 81-user-scripts.sh: executing... 
> [cont-init.d] 81-user-scripts.sh: exited 0.
> [cont-init.d] 82-user-plugins.sh: executing... 
> [cont-init.d] 82-user-plugins.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> starting version 3.2.4
> [services.d] done.
> Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
> Successfully dropped root privileges.
> avahi-daemon 0.6.32 starting up.
> WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
> Successfully called chroot().
> Successfully dropped remaining capabilities.
> No service file found in /etc/avahi/services.
> *** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
> *** WARNING: Detected another IPv6 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
> Joining mDNS multicast group on interface hassio.IPv6 with address fe80::42:2fff:fef4:a59b.
> New relevant interface hassio.IPv6 for mDNS.
> Joining mDNS multicast group on interface hassio.IPv4 with address 172.30.32.1.
> New relevant interface hassio.IPv4 for mDNS.
> Joining mDNS multicast group on interface eth0.IPv6 with address fe80::6b06:8b3c:27a2:db2a.
> New relevant interface eth0.IPv6 for mDNS.
> Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.31.113.
> New relevant interface eth0.IPv4 for mDNS.
> Network interface enumeration completed.
> Registering new address record for fe80::42:2fff:fef4:a59b on hassio.*.
> Registering new address record for 172.30.32.1 on hassio.*.
> Registering new address record for fe80::6b06:8b3c:27a2:db2a on eth0.*.
> Registering new address record for 192.168.31.113 on eth0.*.
> Withdrawing address record for 172.30.32.1 on hassio.
> Withdrawing address record for fe80::6b06:8b3c:27a2:db2a on eth0.
> Withdrawing address record for 192.168.31.113 on eth0.
> Host name conflict, retrying with null-2
> Registering new address record for fe80::42:2fff:fef4:a59b on hassio.*.
> Registering new address record for 172.30.32.1 on hassio.*.
> Registering new address record for fe80::6b06:8b3c:27a2:db2a on eth0.*.
> Registering new address record for 192.168.31.113 on eth0.*.
> Withdrawing address record for 172.30.32.1 on hassio.
> Withdrawing address record for fe80::6b06:8b3c:27a2:db2a on eth0.
> Withdrawing address record for 192.168.31.113 on eth0.
> Host name conflict, retrying with null-3
> Registering new address record for fe80::42:2fff:fef4:a59b on hassio.*.
> Registering new address record for 172.30.32.1 on hassio.*.
> Registering new address record for fe80::6b06:8b3c:27a2:db2a on eth0.*.
> Registering new address record for 192.168.31.113 on eth0.*.
> Withdrawing address record for 172.30.32.1 on hassio.
> Withdrawing address record for fe80::6b06:8b3c:27a2:db2a on eth0.
> Withdrawing address record for 192.168.31.113 on eth0.
> Host name conflict, retrying with null-4
> Registering new address record for fe80::42:2fff:fef4:a59b on hassio.*.
> Registering new address record for 172.30.32.1 on hassio.*.
> Registering new address record for fe80::6b06:8b3c:27a2:db2a on eth0.*.
> Registering new address record for 192.168.31.113 on eth0.*.
> Withdrawing address record for 172.30.32.1 on hassio.
> Withdrawing address record for fe80::6b06:8b3c:27a2:db2a on eth0.
> Withdrawing address record for 192.168.31.113 on eth0.
> Host name conflict, retrying with null-5
> Registering new address record for fe80::42:2fff:fef4:a59b on hassio.*.
> Registering new address record for 172.30.32.1 on hassio.*.
> Registering new address record for fe80::6b06:8b3c:27a2:db2a on eth0.*.
> Registering new address record for 192.168.31.113 on eth0.*.
> Withdrawing address record for 172.30.32.1 on hassio.
> Withdrawing address record for fe80::6b06:8b3c:27a2:db2a on eth0.
> Withdrawing address record for 192.168.31.113 on eth0.
> Host name conflict, retrying with null-6
> Registering new address record for fe80::42:2fff:fef4:a59b on hassio.*.
> Registering new address record for 172.30.32.1 on hassio.*.
> Registering new address record for fe80::6b06:8b3c:27a2:db2a on eth0.*.
> Registering new address record for 192.168.31.113 on eth0.*.
> *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
> *** WARNING *** Please fix your application to use the native API of Avahi!
> *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
> *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
> *** WARNING *** Please fix your application to use the native API of Avahi!
> *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
> Withdrawing address record for 172.30.32.1 on hassio.
> Withdrawing address record for fe80::6b06:8b3c:27a2:db2a on eth0.
> Withdrawing address record for 192.168.31.113 on eth0.
> Host name conflict, retrying with null-7
> Registering new address record for fe80::42:2fff:fef4:a59b on hassio.*.
> Registering new address record for 172.30.32.1 on hassio.*.
> Registering new address record for fe80::6b06:8b3c:27a2:db2a on eth0.*.
> Registering new address record for 192.168.31.113 on eth0.*.
> Withdrawing address record for 172.30.32.1 on hassio.
> Withdrawing address record for fe80::6b06:8b3c:27a2:db2a on eth0.
> Withdrawing address record for 192.168.31.113 on eth0.
> Host name conflict, retrying with null-8
> Registering new address record for fe80::42:2fff:fef4:a59b on hassio.*.
> Registering new address record for 172.30.32.1 on hassio.*.
> Registering new address record for fe80::6b06:8b3c:27a2:db2a on eth0.*.
> Registering new address record for 192.168.31.113 on eth0.*.
> Withdrawing address record for 172.30.32.1 on hassio.
> Withdrawing address record for fe80::6b06:8b3c:27a2:db2a on eth0.
> Withdrawing address record for 192.168.31.113 on eth0.
> Host name conflict, retrying with null-9
> Registering new address record for fe80::42:2fff:fef4:a59b on hassio.*.
> Registering new address record for 172.30.32.1 on hassio.*.
> Registering new address record for fe80::6b06:8b3c:27a2:db2a on eth0.*.
> Registering new address record for 192.168.31.113 on eth0.*.

**Comment by pinksocks** [comment]
Would like to confirm I am having this issue. I attempted to set host-name in config to hassio.

**Comment by frenck** [comment]
The add-on is now deprecated and will only receive minor updates to existing features and software.
Please migrate to the native Home Assistant component.
