### ISSUE TITLE
Questition: How does this project differ from homebridge-homeassistant?

### ISSUE THREAD

**Issue by Madsn** [hassio-addons/addon-homebridge#88]
I'm new to homebridge/homeassistant so I apologize for the stupid question, but is the purpose of this project roughly the same as https://github.com/home-assistant/homebridge-homeassistant ?

**Comment by frenck** [comment]
Well, the goal is to be the same 😉 

This is a prepackaged add-on/docker container for Hass.io type installations.
It gives users a single click installation experience, instead of doing it all manually.
