### ISSUE TITLE
Host name and password.

### ISSUE THREAD

**Issue by fraddygil** [hassio-addons/addon-homebridge#89]
**Question 1**
Hello, I am writing to know why it is necessary to change the host to> http: // hassio / homeasistant?
How could I change it?
Currently my host name is hassio.local: 8123
and I am working correctly with homekit and the iOS application.
Will you have a problem in the future?

My Config.json is default... only changed       "default_visibility"  to "visible".

**Question 2**
In the password they recommend leaving it empty, but I would like to insert a password ... there I have to place the same password that I have put in the configuration file.yaml?

http:
   # Secrets are defined in the file secrets.yaml
   #api_password: ??????

The password here is MD5 encrypt?????

      "platform": "HomeAssistant",
      "name": "HomeAssistant",
      "host": "http://hassio/homeassistant",
      "password": "0aeb6d9f99924f3fbd12998ac03d76c5",

thanks

**Comment by frenck** [comment]
Hi @fradducho,

**Answer to question 1:**
The URL given (`http://hassio/homeassistant`) is an internal Hass.io network. Which is far more efficient to use then connecting to your own URL's (which would go via outside the host).

**Answer to question 2:**
With the URL advised in answer 1, the connection would go over a private connected network. There is not ouside access, so the need for password is less important. Secondly, the add-on will replace the password with an Hass.io API token, which is an MD5 based token (NOT A PASSWORD!).

Hopefully this answers your questions.

Please be sure to use the forums for questions next time 😉
