### ISSUE TITLE
Command line parameters (insecure Mode) not possible

### ISSUE THREAD

**Issue by joergsti** [hassio-addons/addon-homebridge#91]
# Problem/Motivation

It is not possible to set command line parameters for homebridge. For example -I for insecure mode which is needed for Alexa (see https://www.npmjs.com/package/homebridge-alexa). 

## Expected behavior

There should be a setting for command line parameters. 

## Proposed changes
Add command line parameters to config. 

<blockquote><img src="https://static.npmjs.com/338e4905a2684ca96e08c7780fc68412.png" width="48" align="right"><div><img src="https://static.npmjs.com/da3ab40fb0861d15c83854c29f5f2962.png" height="14"> npm</div><div><strong><a href="https://www.npmjs.com/package/homebridge-alexa">homebridge-alexa</a></strong></div><div>Alexa Skill frontend for Homebridge</div></blockquote>

**Comment by frenck** [comment]
Nice!

Thank you for this suggestion.
Adding an option for passing in command line parameters seem a little heavy for the issue at hand.
What I can do, is adding an add-on configuration option: `insecure` (which accepts true or false).

Currently working on migrating all of the Community add-ons. Afterward, I'll add this to the short list.

**Comment by joergsti** [comment]
Thanks!

Is there any way to hardcode it in my installed addon until you added the option?

**Comment by frenck** [comment]
The only option is to fork, modify the homebridge service script and build the add-on manually.

**Comment by frenck** [comment]
The feature has been added to the `master` branch. Will be included in the next release.
