### ISSUE TITLE
The color temperature scale of Xiaomi-Philips LED is not match with homebridge and homeassistant

### ISSUE THREAD

**Issue by mcdull** [hassio-addons/addon-homebridge#92]
# Problem/Motivation

When try to select color temperature of the light in homekit, its behavior is not matching the color show.

## Expected behavior

It is expected to have day night white when select the white color, and yellow when select the yellow. 

## Actual behavior

Only a "range" of the color temperature change the color of the light, not the full scale.  The majority part of the yellow scale has no effect on the light.

## Steps to reproduce

Just pair a Xiaomi Philip ceiling light and control with homekit

> (How can someone else make/see it happen)

Same

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Sorry, no

**Comment by mcdull** [comment]
Sorry. After review, it should be the issue of the homeassistant plugin for homebridge.

**Comment by frenck** [comment]
No problem @mcdull!
