### ISSUE TITLE
Components "No Response" in the Home App - Addon running properly in HA

### ISSUE THREAD

**Issue by CMaxim77** [hassio-addons/addon-homebridge#95]
# Problem/Motivation

> (Why the issue was filed)
This is my first every try at this. Please forgive me if I did not do it correctly.

It seems after the latest update, all of my previous components (scripts, switches, etc.) now appear to be unresponsive. Some times after tapping on it it will start working then after a short time go back to "no response" 

I hope there's a easy fix I have been trying to get this working for a few days now.

thanks everybody!

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by rpetteruti** [comment]
Same behaviour here.

**Comment by rkpatel33** [comment]
I think I am having the same issue. Devices show up for a very very long time as `Updating` immediately after adding them to the Home app, and then eventually become `Unresponsive`. I had this turned off for a long time, but updated and turned on the add-on yesterday.

![image](https://user-images.githubusercontent.com/3799489/41472707-180b24d8-706c-11e8-94c8-68d4de34b129.png)

**Comment by CMaxim77** [comment]
I can’t believe I’m having such a problem trying to find help with this. Luckily for me but unfortunately for you I’m not alone.....

**Comment by GoBooth** [comment]
I'm having the same issue.
you guys think this is because of .71?

would going back to .69 fix the issue?

**Comment by GoBooth** [comment]
the answer is yes, reverting to my .69 snapshot fixed my issue.

**Comment by frenck** [comment]
@GoBooth Did the restoring of the snapshot downgrade the add-on as well?

I'm pretty unsure where to look. There are certainly changes in the underlying mDNS handling, which might be the root cause of this issue.

**Comment by frenck** [comment]
I'm going to downgrade `homebridge` itself, since I highly suspect it to be the root cause of the issue.

**Comment by CMaxim77** [comment]
Is there anything that I will have to do to downgrade? Thanks for looking into this frenck !

**Comment by frenck** [comment]
@CMaxim77 There is nothing for you to do... except having a little patience  😉 

I'm going to test the downgrade today, and if it works as expected, I'll do a minor release right after it.

**Comment by CMaxim77** [comment]
Was this completed? Or is there a way to know that it was?

**Comment by frenck** [comment]
No this is still in progress, meanwhile, Homebridge released a new version (again). So that is another thing to look at.

**Comment by CMaxim77** [comment]
Thanks for the info @frenck

**Comment by frenck** [comment]
I've release `v2.6.1` of the add-on, which includes an updates version of Homebridge (`0.4.44`).

This version has been tested and found to be working (at least on my system & network).

Feel free to re-open or create a new issue if you are still experiencing problems.

**Comment by GoBooth** [comment]
Not sure what fixed it.
but I stayed on .69 until .72 was released.
did the upgrade and everything still works :)

awesome work guys! thank you.!

**Comment by Tomfr06** [comment]
Updated to v2.6.1... still have the very same issue.

**Comment by frenck** [comment]
@Tomfr06 Could you please try the following:

https://github.com/hassio-addons/addon-homebridge#my-ios-app-cannot-find-homebridgehome-assistant


<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-homebridge">hassio-addons/addon-homebridge</a></strong></div><div>addon-homebridge -  Homebridge - Community Hass.io Add-on for Home Assistant</div></blockquote>

**Comment by Tomfr06** [comment]
Had tried already, but retried... some accessories are OK for a little while, then they  all become unresponsive. It looks like it's happening when the Home app tries to refresh a specific room.
Will try to remove plugins gradually to see if I can find a pattern (netatmo, denon, dyson-link).
